services:
  alisub-ng:
    image: ghcr.io/liwei9804/alisub-ng:latest
    container_name: alisub-ng
    restart: unless-stopped
    ports:
      - "8003:8003"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
      - PORT=8003
      - AUTH_USER=admin
      - AUTH_PASS=admin
